---
# argument spec file for v_neyanin.httpscript.start-script-and-check

argument_specs:
  main:
    short_description: Role description.
    options:
      start-script-and-check_my_variable:
        type: str
        description: A simple string argument for demonstration.
        default: "default_value"
